[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "nqrduck"
version = "0.0.2"
authors = [
  { name="Julia Pfitzer", email="git@jupfi.me" },
]

description = "Simple Python script to interact with various python modules used for NQR spectroscopy."
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "matplotlib",
    "pyqt5",
    "pyyaml",
]

[project.optional-dependencies]
nqrduck-autotm = [
    "nqrduck-autotm @ git+https://github.com/jupfi/nqrduck-autotm.git",
]
nqrduck-spectrometer = [
    "nqrduck-spectrometer @ git+https://github.com/jupfi/nqrduck-spectrometer.git",
]
nqrduck-broadband = [
    "nqrduck-broadband @ git+https://github.com/jupfi/nqrduck-broadband.git",
]

[project.gui-scripts]
nqrduck = "nqrduck.__main__:main"